### ISSUE TITLE
Support for local Genbank DB?

### ISSUE THREAD

**Issue by mkweskin** [kaspermunch/sap#1]
Is there a way to use a local download of the Genbank DB rather than using netblast? We're trying to run large batches of queries and netblast is a bottleneck. I see you can use a fasta file for your db and the taxonomy will get parsed and a blastdb will be made, I'm not sure if there's a workaround for a pre-formatted blast DB downloaded from genbank.
Thanks!

**Comment by kaspermunch** [comment]
Hi Matthew,

You can’t run against the entire GenBank locally, but with the most recent version of SAP you can compile a local database of sequences specified by an entrez query.

Go here for the most recent version:

http://services.birc.au.dk/sap

Here is an example of how to make a local database with all COI genes from the Barcode project:

Compiling a local database specified by a query for Genbank nucleotide db:
    sap --compile '(COI[Gene Name]) AND barcode[Keyword]' --database coi_barcode_db.fasta

Running against a local database:
    sap --project myproject --database coi_barcode_db.fasta query.fasta

Cheers,
Kasper

On 22/09/2015, at 21.06, Matthew Kweskin <notifications@github.com<mailto:notifications@github.com>> wrote:

Is there a way to use a local download of the Genbank DB rather than using netblast? We're trying to run large batches of queries and netblast is a bottleneck. I see you can use a fasta file for your db and the taxonomy will get parsed and a blastdb will be made, I'm not sure if there's a workaround for a pre-formatted blast DB downloaded from genbank.
Thanks!
