### ISSUE TITLE
Issues installing on macOS Sierra

### ISSUE THREAD

**Issue by KyleEwart** [kaspermunch/sap#11]
Dear Kasper,

I am having trouble installing SAP on my macOS Sierra. When running "python setup.py install", I receive many warnings, ending with "error: command 'x86_64-apple-darwin13.4.0-clang++' failed with exit status 1".
I've attached the terminal output (error_log1.txt). I can use "sudo python setup.py install" - the output then says the program is installed, but it doesn't appear to install properly.

As a workaround, I tried running "export CXX=clang", then rerunning "python setup.py install". This time a got several different warnings, ending with "error: command 'clang' failed with exit status 1".
I've attached the terminal output (error_log1.txt).

Any help would be much appreciated!

Kind regards,
Kyle
[error_log2.txt](https://github.com/kaspermunch/sap/files/7214958/error_log2.txt)
[error_log1.txt](https://github.com/kaspermunch/sap/files/7214959/error_log1.txt)

**Comment by KyleEwart** [comment]
Note, I receive the same errors when trying the installation on macOS Catalina.

**Comment by kaspermunch** [comment]
Hi Kyle

Did you make the conda environment first?

Best regards,
Kasper Munch
--
Associate professor
Bioinformatics Research Centre
Aarhus University
phone: 8715 6536
On 24 Sep 2021, 01.13 +0200, KyleEwart ***@***.***>, wrote:

Note, I receive the same errors when trying the installation on macOS Catalina.

**Comment by KyleEwart** [comment]
Hi Kasper,

Many thanks for your response.
Yes I made the condo environment following the instructions in https://services.birc.au.dk/sap/downloads

I may have resolved this compilation issue by using:
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
I also upgraded 'app' ('pip install app --upgrade')

This allowed me to install sap - however, I'm not sure if it installed properly as there were some warnings during the compilation.... Do you have an example dataset I could try with some expected results?

I tried running the program using GenBank, but received the same error in 'issue #8.' However, I am more interesting in using the program with a local database. I tried a small local database and an example sequence - see the attached files I used (note, I had to change them to txt files to attach). I tried a few different commands, but got furthest with this one:
sap --project TestingProject --database ref_database.fasta example_unknown.fasta --fillinall --minimaltaxonomy 1 --forceincludefile seqs_include.txt
The error seems to be occurring here:
System call "clustalw2 -infile=16jls1.tmp.fasta -output=NEXUS -gapopen=50 -outfile=16jls1.tmp" return code 255
Could not find/read file: /Applications/sap/16jls1.tmp

However, this error might be separate from the compilation issue... It would be helpful to verify if sap working as expected with an example local dataset.

Kind regards,
Kyle

[example_unknown.txt](https://github.com/kaspermunch/sap/files/7255911/example_unknown.txt)
[ref_database.txt](https://github.com/kaspermunch/sap/files/7255912/ref_database.txt)
[seqs_include.txt](https://github.com/kaspermunch/sap/files/7255913/seqs_include.txt)

**Comment by kaspermunch** [comment]
Hi Kyle,

I have made a Docker image of sap. That should work on any machine. You just install Docker Desktop and then run:

docker run --rm -v $PWD:/mnt kaspermunch/sap:latest [ARGUMENTS]

Instead of the usual:

sap [ARGUMENTS]

You can make put an alias in your .profile or .zprofile:

alias sap='docker run --rm -v $PWD:/mnt kaspermunch/sap:latest'

to let you do: sap [ARGUMENTS]

The advantage is that the user don’t need to do any compilation as the whole thing is done on an Ubuntu image.

If you are on a cluster where Docker is not available you can use Singularity instead: https://hub.docker.com/r/uvarc/smcpp.

If it works as expected, I will add it as the new installation instruction.

Best regards,
Kasper Munch
--
Associate professor
Bioinformatics Research Centre
Aarhus University
phone: 8715 6536
On 30 Sep 2021, 03.33 +0200, KyleEwart ***@***.***>, wrote:

Hi Kasper,

Many thanks for your response.
Yes I made the condo environment following the instructions in https://services.birc.au.dk/sap/downloads

I may have resolved this compilation issue by using:
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
I also upgraded 'app' ('pip install app --upgrade')

This allowed me to install sap - however, I'm not sure if it installed properly as there were some warnings during the compilation.... Do you have an example dataset I could try with some expected results?

I tried running the program using GenBank, but received the same error in 'issue #8<https://github.com/kaspermunch/sap/issues/8>.' However, I am more interesting in using the program with a local database. I tried a small local database and an example sequence - see the attached files I used (note, I had to change them to txt files to attach). I tried a few different commands, but got furthest with this one:
sap --project TestingProject --database ref_database.fasta example_unknown.fasta --fillinall --minimaltaxonomy 1 --forceincludefile seqs_include.txt
The error seems to be occurring here:
System call "clustalw2 -infile=16jls1.tmp.fasta -output=NEXUS -gapopen=50 -outfile=16jls1.tmp" return code 255
Could not find/read file: /Applications/sap/16jls1.tmp

However, this error might be separate from the compilation issue... It would be helpful to verify if sap working as expected with an example local dataset.

Kind regards,
Kyle

example_unknown.txt<https://github.com/kaspermunch/sap/files/7255911/example_unknown.txt>
ref_database.txt<https://github.com/kaspermunch/sap/files/7255912/ref_database.txt>
seqs_include.txt<https://github.com/kaspermunch/sap/files/7255913/seqs_include.txt>

**Comment by kaspermunch** [comment]
Hi again,

The command is

docker run --rm -v $PWD:/code/sap kaspermunch/sap:latest

not

docker run --rm -v $PWD:/mnt kaspermunch/sap:latest

Sorry about that.

Best regards,
Kasper Munch
--
Associate professor
Bioinformatics Research Centre
Aarhus University
phone: 8715 6536
On 4 Oct 2021, 18.48 +0200, Kasper Munch Terkelsen ***@***.***>, wrote:
Hi Kyle,

I have made a Docker image of sap. That should work on any machine. You just install Docker Desktop and then run:

docker run --rm -v $PWD:/mnt kaspermunch/sap:latest [ARGUMENTS]

Instead of the usual:

sap [ARGUMENTS]

You can make put an alias in your .profile or .zprofile:

alias sap='docker run --rm -v $PWD:/mnt kaspermunch/sap:latest'

to let you do: sap [ARGUMENTS]

The advantage is that the user don’t need to do any compilation as the whole thing is done on an Ubuntu image.

If you are on a cluster where Docker is not available you can use Singularity instead: https://hub.docker.com/r/uvarc/smcpp.

If it works as expected, I will add it as the new installation instruction.

Best regards,
Kasper Munch
--
Associate professor
Bioinformatics Research Centre
Aarhus University
phone: 8715 6536
On 30 Sep 2021, 03.33 +0200, KyleEwart ***@***.***>, wrote:

Hi Kasper,

Many thanks for your response.
Yes I made the condo environment following the instructions in https://services.birc.au.dk/sap/downloads

I may have resolved this compilation issue by using:
export CC=/usr/bin/clang
export CXX=/usr/bin/clang++
I also upgraded 'app' ('pip install app --upgrade')

This allowed me to install sap - however, I'm not sure if it installed properly as there were some warnings during the compilation.... Do you have an example dataset I could try with some expected results?

I tried running the program using GenBank, but received the same error in 'issue #8<https://github.com/kaspermunch/sap/issues/8>.' However, I am more interesting in using the program with a local database. I tried a small local database and an example sequence - see the attached files I used (note, I had to change them to txt files to attach). I tried a few different commands, but got furthest with this one:
sap --project TestingProject --database ref_database.fasta example_unknown.fasta --fillinall --minimaltaxonomy 1 --forceincludefile seqs_include.txt
The error seems to be occurring here:
System call "clustalw2 -infile=16jls1.tmp.fasta -output=NEXUS -gapopen=50 -outfile=16jls1.tmp" return code 255
Could not find/read file: /Applications/sap/16jls1.tmp

However, this error might be separate from the compilation issue... It would be helpful to verify if sap working as expected with an example local dataset.

Kind regards,
Kyle

example_unknown.txt<https://github.com/kaspermunch/sap/files/7255911/example_unknown.txt>
ref_database.txt<https://github.com/kaspermunch/sap/files/7255912/ref_database.txt>
seqs_include.txt<https://github.com/kaspermunch/sap/files/7255913/seqs_include.txt>

**Comment by KyleEwart** [comment]
Hi Kasper,

Running the program through docker seems to work well. This will be very handy for me when I’m switching between computers.

Unfortunately my specific analysis is still not working. Evidently it appears to be something wrong with what I’m trying to run, rather than a compilation issue.

I am getting a “Not enough significant homologues found” message, even though several of the reference sequences are from the same species as my ‘unknown’ sequence. I believe it could be due to the small reference database I am using (35 sequences, 10 of which are from the same species as my unknown), which I’m assuming is atypical when using sap? I don’t seem to be able to include all reference sequences in the analysis (i.e. the alignment and tree). 

NB: apologies – I realize that this is a separate issue to original one I posted. I will keep fiddling with the different sap options to try get it to work, but if you think it’s not suitable for this specific application (i.e. a species ID with a relatively small database), please let me know.

Thanks for all of your responses!

Cheers,
Kyle

**Comment by kaspermunch** [comment]
Hi Kyle,

You are venturing into the unknown territory there. The short answer is that you can use the —nrsignificant option to change the minimum required number of significant homologs found to proceed with the analysis. There are also options to control many other aspects of how the set of homologues is compiled.

The longer answer is that sap will only provide you with a posterior distribution of assignments to taxa in represented in our set of homologs. The reason the default parameters are as they are is to construct a set with so much taxonomic diversity that some of them will end up with an assignment probability of zero. Normally sap only includes one individual from each species, but you can include 10 by using —individuals 10 option. There are also options to control other things. You can see them all here:

https://github.com/kaspermunch/sap/blob/master/SAP/Options.py

Best regards,
Kasper Munch
--
Associate professor
Bioinformatics Research Centre
Aarhus University
phone: 8715 6536
On 5 Oct 2021, 10.06 +0200, KyleEwart ***@***.***>, wrote:

Hi Kasper,

Running the program through docker seems to work well. This will be very handy for me when I’m switching between computers.

Unfortunately my specific analysis is still not working. Evidently it appears to be something wrong with what I’m trying to run, rather than a compilation issue.

I am getting a “Not enough significant homologues found” message, even though several of the reference sequences are from the same species as my ‘unknown’ sequence. I believe it could be due to the small reference database I am using (35 sequences, 10 of which are from the same species as my unknown), which I’m assuming is atypical when using sap? I don’t seem to be able to include all reference sequences in the analysis (i.e. the alignment and tree).

NB: apologies – I realize that this is a separate issue to original one I posted. I will keep fiddling with the different sap options to try get it to work, but if you think it’s not suitable for this specific application (i.e. a species ID with a relatively small database), please let me know.

Thanks for all of your responses!

Cheers,
Kyle

**Comment by KyleEwart** [comment]
Hi Kasper,

Thanks for these recommendations. Unfortunately it is still getting stuck at the clustalw2 step:
System call "clustalw2 -infile=ambwa6.tmp.fasta -output=NEXUS -gapopen=50 -outfile=ambwa6.tmp" return code 255
Could not find/read file: /code/sap/ambwa6.tmp

Thanks for all of your feedback on this. I will keep having a play around with different parameter combinations to try get it working. Although I am using the program for a different application to what it was written for, the method looks to be an effective approach to perform species identifications in general.

Cheers,
Kyle

**Comment by kaspermunch** [comment]
Hi Kyle,

It sounds the mount between your current directory and /code/sap in the container was not set up. Are you sure $PWD expands to your current directory? Try echo $PWD. If not you can try:

docker run --rm -v `pwd`:/code/sap kaspermunch/sap:latest [ARGUMENTS]

Are you running this on Mac/linux or windows?

Best regards,
Kasper Munch
--
Associate professor
Bioinformatics Research Centre
Aarhus University
phone: 8715 6536
On 7 Oct 2021, 06.59 +0200, KyleEwart ***@***.***>, wrote:

Hi Kasper,

Thanks for these recommendations. Unfortunately it is still getting stuck at the clustalw2 step:
System call "clustalw2 -infile=ambwa6.tmp.fasta -output=NEXUS -gapopen=50 -outfile=ambwa6.tmp" return code 255
Could not find/read file: /code/sap/ambwa6.tmp

Thanks for all of your feedback on this. I will keep having a play around with different parameter combinations to try get it working. Although I am using the program for a different application to what it was written for, the method looks to be an effective approach to perform species identifications in general.

Cheers,
Kyle

**Comment by KyleEwart** [comment]
Hi Kasper, 
It’s working! I think the previous error arose due to some issues with my local database (I have now removed all characters other than letters/numbers). The docker command is also working using the NCBI database :) NB: I am using a Mac.

Apologies - I have one last question on this. It’s not clear how the '--bayesfactors' option works. I can’t see any results for Bayes Factors when using this option, only a short what different Bayes Factors represent (e.g. '10 to 30 - Strong'). Are there files created during the analysis that will have Bayes Factor information. I basically want to see how the assignment posterior probability of the assigned species compares with closely related species included in the analysis. For example, in the example online on the SAP web server (https://services.birc.au.dk/sap/clone/example_Y7IQXN/exampleY7IQXNshow_327419596), the example sequence forms a monophyletic group with Panthera Leo with a posterior probability = 100%. Where can I find the posterior probability of the sequence forming a monopheletic group with Panthera pardus for example? Or is this a conditional probability; e.g. if the sequence formed a monophyletic group with Panthera leo wth a posterior probability of 95%, any other species assignment will be maximum 5%?

Apologies for so many questions on this, and thank you for your help.

Cheers,
Kyle

**Comment by kaspermunch** [comment]
Hi Kyle,

Good to hear. You can read about how posterior probabilities are assigned in the paper in Systematic Biology. The bases factor was an experiment I did a long time ago. It is not supported.

Best regards,
Kasper Munch
--
Associate professor
Bioinformatics Research Centre
Aarhus University
phone: 8715 6536
On 13 Oct 2021, 02.34 +0200, KyleEwart ***@***.***>, wrote:

Hi Kasper,
It’s working! I think the previous error arose due to some issues with my local database (I have now removed all characters other than letters/numbers). The docker command is also working using the NCBI database :) NB: I am using a Mac.

Apologies - I have one last question on this. It’s not clear how the '--bayesfactors' option works. I can’t see any results for Bayes Factors when using this option, only a short what different Bayes Factors represent (e.g. '10 to 30 - Strong'). Are there files created during the analysis that will have Bayes Factor information. I basically want to see how the assignment posterior probability of the assigned species compares with closely related species included in the analysis. For example, in the example online on the SAP web server (https://services.birc.au.dk/sap/clone/example_Y7IQXN/exampleY7IQXNshow_327419596), the example sequence forms a monophyletic group with Panthera Leo with a posterior probability = 100%. Where can I find the posterior probability of the sequence forming a monopheletic group with Panthera pardus for example? Or is this a conditional probability; e.g. if the sequence formed a monophyletic group with Panthera leo wth a posterior probability of 95%, any other species assignment will be maximum 5%?

Apologies for so many questions on this, and thank you for your help.

Cheers,
Kyle
