### ISSUE TITLE
Underscores in sequence

### ISSUE THREAD

**Issue by ekrell** [kaspermunch/sap#5]
Example: https://www.ncbi.nlm.nih.gov/nuccore/NC_031406.1/

Causes SAP to crash since the underscore is used to separate in SAP: 

So the following fails with dictionary error since it can't look up 'NC'
```
gi, organism = taxonName.split("_", 1)
taxonomy = homologyResult.homologues[gi].taxonomy
```

I will try a hack by either replacing the extra underscores with another character or by having SAP use something like three underscores as the separator. Whichever seems easier.

**Comment by ekrell** [comment]
The quick fix is to make sure there are no underscores in the input database.
I believe the problem is that various NCBI databases are merging into nucleotide, using a prefix such as 'NC_'. So users like myself are running into this where we never did before. Not really an issue with SAP itself, but something other SAP users might encounter.

**Comment by kaspermunch** [comment]
Hi Evan,

Thanks for the heads up. Glad to hear you found a work-around. I do not think the local database functionality is used that much, but I will see if I can find time to fix it.

VH Kasper
On 8 Jul 2019, 20.35 +0200, Evan Krell <notifications@github.com>, wrote:

The quick fix is to make sure there are no underscores in the input database.
I believe the problem is that various NCBI databases are merging into nucleotide, using a prefix such as 'NC_'. So users like myself are running into this where we never did before. Not really an issue with SAP itself, but something other SAP users might encounter.
